### ISSUE TITLE
Returned character data incorrect for characters who have a class unlocked but not its job

### ISSUE THREAD

**Issue by robotbrain** [xivapi/lodestone-parser#8]
Example character meeting the above condition (on marauder in this case)
https://na.finalfantasyxiv.com/lodestone/character/25026951/

Data returned (xivapi link used since its a direct return pretty much)
https://xivapi.com/character/25026951?extended=1&data=cj,fc

Potential fix outline: the tooltip for the class/job icon on the character lodestone page is correctly set to the name of the class or job

**Comment by viion** [comment]
Hello,

I'm a bit confused, which bit is not returned correctly? It shows Active Class correct as Marauder, and lists their job/classes correct.

Is there a specific bit of data which is incorrect?

**Comment by robotbrain** [comment]
Both the ActiveClassJob section and the full ClassJobs section have both the class and the job described in each entry, 
![image](https://user-images.githubusercontent.com/3117019/83361897-e904a000-a35a-11ea-86f3-b9bc75d27780.png) even in this case where the character is not a warrior, there is still a job entry in the classjob info that says warrior, and theres no information as to whether the character has that even unlocked

**Comment by viion** [comment]
This is intended, it's just the class/job entry, it has no meaning to what the current role is (weather that be the class or the job).

Unlikely to be fixed because you can use the job stone entry in gear to know if they're on class or job: https://xivapi.com/character/25026951?extended=1&data=cj,fc&columns=Character.GearSet.Gear.SoulCrystal

vs job: https://xivapi.com/character/9251709?extended=1&data=cj,fc&columns=Character.GearSet.Gear.SoulCrystal

**Comment by robotbrain** [comment]
I wasnt talking about the active job, for which the job stone is viable, but for the list of classjobs, where the information is not available from other sources from your api and is available from scraping lodestone
